### ISSUE TITLE
NTLMv2 support

### ISSUE THREAD

**Issue by mragaei** [requests/requests-ntlm#71]
Hello,

Thanks for your efforts but I believe NTLMv2 is still not supported in python-ntlm3 and python-ntlm as appears from traffic captures and from reported issues in respective repositories:

https://github.com/trustrachel/python-ntlm3/issues/10
https://github.com/mullender/python-ntlm/issues/47

Issues were reported since quite a while so I hope there's some sort of an alternative as many projects are depending on it.

**Comment by Lukasa** [comment]
As far as I know there is no library that supports NTLMv2. I don't know that anyone will write one either: it's old and deprecated and broken. If an actual project appears that supports it we can reopen the issue, but otherwise I think it might be worthwhile migrating to Kerberos.

**Comment by mragaei** [comment]
Thanks @Lukasa for the fast response though it's a bit disappointing.

Not sure if you have come across the work done by @ianclegg in ntlmlib (https://pypi.python.org/pypi/ntlmlib). If you haven't, please have a look and let me know if we can make use of it to add NTLMv2 support.

**Comment by rbcarson** [comment]
@mragaei One major obstacle to improvements to requests-ntlm is the lack of servers to test against. If you could provide access to a server that requires NTLMv2 authentication, or instructions on how to set one up, that would help with this problem.

The API exposed by ntlmlib is quite different from python-ntlm(3), so rewriting requests-ntlm to use it may require significant effort. If you're comfortable with making an attempt at this, it'd be much appreciated.

**Comment by ianclegg** [comment]
@Lukasa I have an implementation of requests-ntlm using ntlmlib if you are interested in a PR? Its been in production at a number of sites.

**Comment by sigmavirus24** [comment]
@ianclegg do you have a way for us to set up a server with NTLMv2 easily that we can test against? 

As an aside, does ntlmlib support Python 3 and Python 2?

**Comment by sigmavirus24** [comment]
I just checked, it supports up to 3.3 according to classifiers. My major problem with ntlmlib as it stands now, is that it does not explicitly state support for 3.4 and 3.5 **and**, more importantly, it uses PyCrypto. Why is it using PyCrypto instead of [cryptography](/pyca/cryptography)?

**Comment by ianclegg** [comment]
No particular reason, cryptography probably hadn't finished being baked when I first cut the code a few years back. I only open sourced ntlmlib recently since a lot of people I knew were asking for it. NTLMv1 has been disabled by default in all Windows editions for the last 10 years (since Vista).

I don't see a particular problem with using cryptography or supporting python 3.4 and later in ntlmlib - I can take a look if your interested? An alternative might be for me to open source and publish the requests-ntlmv2 handler we have been using separately?

**Comment by ianclegg** [comment]
@sigmavirus24 had a quick look - cryptography looks sound, though it doesn't support MD4 (they might take a PR for it for completeness) - not a deal breaker since its also available though hashlib

**Comment by mragaei** [comment]
@rbcarson , @sigmavirus24 it seems someone's prayers have been answered. I found that @savonrb has already shared a testing plan here:
https://github.com/savonrb/httpi/wiki/NTLM-Integration-Test-Plan

I didn't try it but it looks easy to follow.

To force NTLMv2 you might need to check these articles as well:
https://kb.iu.edu/d/atcb
https://technet.microsoft.com/en-us/library/jj852207(v=ws.11).aspx
https://www.iis.net/configreference/system.webserver/security/authentication/windowsauthentication

@ianclegg thanks a lot for your feedback, I'm sure your contribution would make the job much easier

**Comment by rbcarson** [comment]
@mragaei There's nothing particular to NTLMv2 in the test plan that you linked, as far as I can tell. I already use requests-ntlm against a Windows Server 2012 IIS instance set up the same way, and it works. I'll take a look at the pages about forcing NTLMv2, though.

@ianclegg You say that NTLMv1 has been disabled since Vista, but this seems a bit weird to me. If python-ntlm(3) doesn't support NTLMv2, then what flavour of NTLM is being used when I use requests-ntlm with IIS 8?

**Comment by mragaei** [comment]
@rbcarson I misunderstood that you need to set up the whole testing environment from scratch. Since you have one already in place, I guess all you need to do is to adjust the "Network security: LAN Manager authentication level" setting in the Local Security Policy of the client, server, and domain controller (if exists) to become "Send NTLMv2 response only. Refuse LM & NTLM", which is equivalent to setting the "HKLM\SYSTEM\CurrentControlSet\Control\Lsa\LMCompatibilityLevel" registry key to "5" as described in the articles mentioned earlier

**Comment by ianclegg** [comment]
@rbcarson Its all about user hashes - no microsoft client or server product will send user hashes in a v1 response. Having worked for Microsoft, the only reason edge facing products like IIS still permit incoming v1 is to support ancient 3rd party products build by firms that no longer exist. So if folks want to send their credentials in v1 hashes, the server will still accept them - it took yours.

If its not clear already, there is nothing you need to do to enable NTLMv2, you can test it right now - just check the header flags in wire shark - 'use the force'

@mragaei Although I strongly recommend disabling NTLMv1, its not necessary to do the testing. ntlmlib has a 'pit of success' it will do NTLMv2 with the strongest negotiated mechanisms by default. If your interested I'll throw you over the code for the auth handler we have - it has the added benefit of not sending over the content body until the authentication is complete

**Comment by mragaei** [comment]
@ianclegg sure I'm interested in your handler specially if it won't force me to give up using requests. At the same time I encourage the requests-ntlm team to consider your PR proposal as python-ntlm(3) seems to be deserted and is no longer being maintained

**Comment by sigmavirus24** [comment]
@ianclegg if you already have the code written, I'd be interested to see how significant of a change it would be to requests-ntlm to support it. You are, of course, also welcome to maintain your own auth package for it though.

**Comment by sigmavirus24** [comment]
@mragaei python-ntlm3 should not be deserted. It is maintained by an employee for that company. If features are rejected it's because that company likely does not see value in spending development time on those features at the moment (unless someone else does the work to include them).

**Comment by ianclegg** [comment]
@mragaei  Extracted it from a larger source file, but it should build. Don't sweat the unit tests, i'll open source them shortly.
https://gist.github.com/ianclegg/a77e309e051ec6cc28eac3c7ab14991b

@sigmavirus24 That handler is not derived from requets-ntlm so there's little if any in common, a patch to requests-ntlm could be made more harmonious. Its matter of creating the ntlm context generator, then feeding the tokens in and out to complete the context exchange during `retry_using_http_NTLM_auth`

**Comment by mragaei** [comment]
@ianclegg I've given it a try but got an exception ending with:

.
    token = context_generator.send(None)
  File "....\ntlmlib\context.py", line 90, in initialize_security_context
    negotiate_token = self._negotiate(self.flags)
  File "....\ntlmlib\context.py", line 144, in _negotiate
    return Negotiate(flags, self._authenticator.get_domain(), self._hostname).get_data()
  File "....\ntlmlib\messages.py", line 214, in get_data
    return Structure.get_data(self)
  File "....\ntlmlib\structure.py", line 130, in get_data
    data += self.pack_field(field[0], field[1])
TypeError: ("Can't convert 'bytes' object to str implicitly", "When packing field 'message_type | <L=1' in <class 'ntlmlib.messages.Negotiate'>")

Have I done something wrong?

**Comment by ianclegg** [comment]
@mragaei I had a quick look into this morning, its a python 3.x issue with the build of ntlmlib on the public pypi. We fixed it onsite a while back, I probably won't get time to push the latest build of ntlmlib until this weekend - out of interest what Python version are you using? Is it 3.5?

**Comment by mragaei** [comment]
@ianclegg this is making sense as the Python version I used for testing is 3.4.3, looking forward to the latest build of ntlmlib :)

**Comment by ianclegg** [comment]
@mragaei Pushed the latest sources and the new build to PyPi (v0.71)
`pip install --upgrade ntlmlib`

- [x] fixed any issues I found with python 3.4 and 3.5 support and updated PyPi classifiers 
- [x] travis build now runs against python 3.4 and python 3.5 (99% code coverage of authentication)
- [x] swapped out pycrypto for cryptography at the behest of @sigmavirus24

I had to make a very minor tweak to the gist
https://gist.github.com/ianclegg/a77e309e051ec6cc28eac3c7ab14991b/revisions

**Comment by mragaei** [comment]
@ianclegg sorry I couldn't get back to you earlier. I tested the new build and now it throws "The remote server rejected NTLM negotiation":

.
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 597, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 582, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\Python34\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "....\authentication.py", line 80, in handle_response
    response = self.handle_401(response, **kwargs)
  File "....\authentication.py", line 71, in handle_401
    client_request = ntlm_processor.send(response)
  File "....\authentication.py", line 50, in _ntlm_processor
    raise NtlmAuthenticationError("The remote server rejected NTLM negotiation")
exceptions.NtlmAuthenticationError: The remote server rejected NTLM negotiation

Fiddler shows it fails at Message 2 of NTLM negotiation as the server does not respond with a challenge.

This is how the code looks like:

import requests
from authentication import HttpNtlm2Auth
session = requests.Session()
r1 = session.get(url1, verify=False)
Referer = dict(Referer = r1.url)
session.auth = HttpNtlm2Auth(DOMAIN, USER, password)
r2 = session.get(url2, verify=False, headers=Referer)

Have I missed something?
Please provide a sample usage code if possible.

**Comment by rbcarson** [comment]
Could someone point me to a service/product that often/always requires NTLMv2?

**Comment by ianclegg** [comment]
@mragaei That should work, I'll post a worked example shortly.

@rbcarson That's not so easy - the decision to 'require' NTLMv2 in any given Windows deployment is made by system administrators. Microsoft's default position on this is for Administrators to disable NTLMv1. The last few clients I have worked for followed this advice - that is raison d'etre for ntlmlib.
https://support.microsoft.com/en-gb/kb/2793313

**Comment by ianclegg** [comment]
I notice you using connection pooling, I assume your aware of the potential security issues with NTLM there (the fact that a security context you negotiated is associated with the underlying tcp connection; which is returned to a pool and would affect whoever uses it next). libcurl used to have this issue a few years back and I looking at the code - I suspect requests has it too?

**Comment by Lukasa** [comment]
Requests absolutely does connection pool.

Ideally requests-ntlm would not allow connections to be put back in to the pool. There is definitely a security risk in using NTLM in this manner. However, it's difficult to deal with: NTLM simply does not authenticate the way HTTP expects to be authenticated.

I'm open to providing hooks into Requests to tweak the behaviour as needed, but it's going to continue to be an impedance mismatch. My recommendation: use one Session per NTLM authentication context.

**Comment by ianclegg** [comment]
good advice

**Comment by ianclegg** [comment]
yer, ntlm has been a pain for most implementer's - the slightly good news, if folks weren't aware - is that Microsoft are not implementing ntlm over http/2

**Comment by ianclegg** [comment]
While we are on the topic, this issue of security contexts and tcp connection reuse can also affect Windows servers using the Negotiate scheme (SPNEGO) which is popular on Windows Domains. Windows Administrators can configure IIS to persist the context for connections that have used Negotiate too, but you'll have to inspect the response for the 'Persistent-Auth' header to determine if this is case, most implementors are simply not aware of this behavior (and who can blame them). The gory details are in MS-N2HT https://msdn.microsoft.com/en-us/library/dd341152.aspx

**Comment by mragaei** [comment]
@rbcarson I suppose your question implies that you tried adjusting the server/DC security policy or registry key to force NTLMv2 but for some reason that didn't take effect, please confirm

@Lukasa, @ianclegg I'm not quite familiar with the innerworkings of NTLM and requests so please shed more light on how to use one Session per NTLM authentication context, keeping in mind that:

- I do not have control over the server and cannot change its settings accordingly
- I need to carry session information (cookies, Referers, etc...) across successive requests
- the security risk associated with connection pooling is not much of a concern in my case, at least for the time being
- with requests-ntlm I managed to get a challenge from the server and failure was occurring at Message 3 of NTLM negotiation (response to server challenge was significantly different and smaller in size than in IE/Firefox case)
- with authentication.py failure occurs at Message 2 as mentioned earlier

@ianclegg you mentioned previously that you have an implementation of requests-ntlm using ntlmlib, would you mind sharing it as well?

**Comment by ianclegg** [comment]
@mragaei - I spotted a possible issue in ntlmlib's setup.py which may have prevented the upgrade. It might be worth trying to removing ntlmlib and reinstalling it? 
`pip uninstall ntlmlib`
`pip install ntlmlib`

run a `pip list` and you see:  ntlmlib (0.72)

I've just spun up a Windows 2008 R2 server on AWS, installed IIS 8 and configured a virtual directory with Windows Authentication (i'll leave the host up a few days)

`[public]`  http://52.208.44.235/iisstart.htm
`[secure]`  http://52.208.44.235/secure/iisstart.htm

I've pushed the ntlm2 auth handler in the gist to a new repo:
https://github.com/ianclegg/requests-ntlm2

If you clone it, and install with:
`python setup.py develop`

I put together a test for your scenario
`python ./test/test_integration.py`

```
import requests
from requests_ntlm2 import HttpNtlm2Auth

# test for mragaei
session = requests.Session()

# un-authenticated
r1 = session.get("http://52.208.44.235/iisstart.htm", verify=False)
Referer = dict(Referer = "http://192.168.1.20/now")

# set auth handler for authenticted, use same connection
session.auth = HttpNtlm2Auth('WIN-QRD0D23AHH3', 'test', '6N%9rEpFqedKdjGw')
r2 = session.get("http://52.208.44.235/secure/iisstart.htm", verify=False, headers=Referer)
print(r2.status_code)
print(r2.content)
```

If everything goes ok you'll see a 200 status code and the request content.

**Comment by Lukasa** [comment]
So after thinking about it longer, there's an even better bit of advice: if possible, use one `TransportAdapter` per target. That is, for each domain you need to NTLM authenticate to, mount a [HTTPAdapter](http://docs.python-requests.org/en/master/user/advanced/#transport-adapters) into the session at that domain (e.g. `https://my-inner-host`). That will limit the scope of connection pooling to that host.

**Comment by mragaei** [comment]
@ianclegg really appreciating the effort you're putting into this but I'm unable to access the test host, may be I'm a bit too late and you shut it down already? Alternatively, can you provide client side packet capture and/or [HTTP Archive file](https://toolbox.googleapps.com/apps/har_analyzer/) for your test so I can compare it against my case?

**Comment by ianclegg** [comment]
@mragaei Try that AWS host again, I had some networking rules which might be blocking access

**Comment by mragaei** [comment]
@ianclegg Thanks, your AWS host is accessible now and I could use requests-ntlm2 with updated ntlmlib to test it successfully, except that it succeeds no matter what value I put for the domain, probably because it's local authentication.

On the other hand, the situation didn't improve for my server as I'm still getting "The remote server rejected NTLM negotiation" exception at Message 2.

The following comparison of Message 2 sent from different clients might give an indication why it's failing:

- IE / FF (succeeds after Message 3):
NTLMSSP

- requests-ntlm via python-ntlm3 (fails after Message 3):
NTLMSSP4((
[computer name][domain]

- requests-ntlm2 via ntlmlib (fails after Message 2):
NTLMSSP0  "[domain][computer name]

**Comment by ianclegg** [comment]
@mragaei Yup - its sounds insane, but the domain name behavior is NTLMv2 alright.

NTLMv2 re-purposes and extends NTLMv1 to retain necessary compatibility. The Negotiate Type1 is pretty much the same for both protocols. The client still sends its domain name in the Type 1 structure - however, in NTLMv2, its is _ignored_. Instead the server responds with its Domain Name in the TargetInfo structure in the Type 2 message - and it is this domain name which forms part of the raw material for the hash.
Also, ordering of the domain name and computer name is also not important as long as the offset and length of the names are correctly set following the header. 

I'm sure there is an issue here, but it's probably very subtle. I really need to take a look at the raw message exchange between ntlmlib and the server in question. Are you able to email me a packet capture (tcpdump or wireshark)?

**Comment by mragaei** [comment]
Not sure how it happened exactly but when I retested requests-ntlm via python-ntlm3 it just worked! As mentioned earlier, I do not have control over the server so I assume that NTLMv1 has been enabled eventually.

@ianclegg I'd like to provide a packet capture but the traffic is SSL protected so it wouldn't be of any use.

According to http://davenport.sourceforge.net/ntlm.html#theType1Message, "Domain" and "Workstation" fields are optional in NTLM Type 1 Message so given that authentication always succeeds with IE/FF/Chrome and they all provide neither in their Type 1 Messages, don't you think that the same should be done when implementing NTLM over HTTP as in requests-ntlm and requests-ntlm2 cases?

**Comment by rbcarson** [comment]
@mragaei You should be able to decrypt the SSL traffic if you use Fiddler and use the HTTPS decryption option with the Fiddler certificate. Also, to answer your previous question, I was just curious if there were products out there that require NTLMv2 in its default configuration. I haven't tried configuring IIS to require it, but I have no doubts that it would work.

**Comment by rbcarson** [comment]
@Lukasa Since this is a work in progress now, should this issue be reopened?

**Comment by Lukasa** [comment]
Why not?

**Comment by jborean93** [comment]
I am preparing to create a pull request to python-ntlm3 to add NTLMv2 support in the library. Thanks to @ianclegg for his wonderful work in his library and just scouring the MS-NLMP documents I believe I have been able to get it working in that library. Just need to tidy up a few things and make it more presentable than the mess it is currently in right now.

Hopefully this will make it easy to add Channel Binding Tokens as that required NTLMv2 which it didn't support before.

**Comment by ianclegg** [comment]
@jborean93 Have you implemented channel binding in ntlmlib? I'd be interested to see the patch - I was going to look into myself this weekend.

**Comment by jborean93** [comment]
Unfortunately no, I haven't tested that component yet as I am trying to make the current changes up to scratch before trying. Theoretically based on the documentation and what I found in your library and the ruby one it should work but judging how my previous changes went there will be some more work required.

I had a quick look at the documentation and from what I understand I need to use the GSS api or pass it on from outside python-ntlm3. I don't quite understand how to check the challenge message (or GSS after receiving the message) to see if the server requires the tokens or not.

The other side I am not sure on how to do is interacting with the GSS Api. Is this a Windows only api or can it be used on all hosts. Hopefully in time I can understand it more.

**Comment by ianclegg** [comment]
@jborean93 More time always helps. [GSS API is a high-level, imperative (C style) API specification](https://tools.ietf.org/html/rfc2743), there are implementations for various authentication mechanisms (normally in C/C++) on Linux and Windows. The NTLM protocol spec's refer to a Microsoft specific GSS implementation provided in Win32's SSPI and ultimately implemented in the various security package's shipped with Windows.

> I don't quite understand how to check the challenge message (or GSS after receiving the message) to see if the server requires the tokens or not.

You cant tell if you need to send one of not. If your doing NTLMv2, you should include it, servers not configured with Extended Protection will just ignore it.

**Comment by jborean93** [comment]
Have finally gotten a pull request happening to add NTLMv2 support https://github.com/trustrachel/python-ntlm3/pull/21. It will ultimately require some changes to requests-ntlm as it currently doesn't have the necessary information right now to support it.

Hopefully the owner is still active and we can look at this pull request and make the changes required to get this in and packaged.

@ianclegg thanks very much for the info, I am focusing on getting this pull request in and then will look at CBT.

**Comment by jborean93** [comment]
Sorry for spamming this thread but I have updated my pull request to also include Channel Binding Tokens. I have managed to get it working and have added the changes to my pull request.

**Comment by jborean93** [comment]
NTLMv2 auth support has been added with https://github.com/requests/requests-ntlm/pull/84.
